const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "JoltPhysics",
        .target = target,
        .optimize = optimize,
    });

    lib.addCSourceFiles(.{
        .root = b.path("Jolt"),
        .flags = &.{"-std=c++17"},
        .files = &base_src_files,
    });
    lib.linkLibCpp();
    lib.addIncludePath(b.path("./"));
    lib.installHeadersDirectory(b.path("Jolt"), "Jolt", .{
        .include_extensions = &.{ ".h", ".inl" },
    });

    b.installArtifact(lib);

    {
        const step = b.step("hello_world", "Runs HelloWorld");
        const exe = b.addExecutable(.{
            .name = "Hello World",
            .target = target,
            .optimize = b.standardOptimizeOption(.{ .preferred_optimize_mode = .ReleaseSafe }),
        });
        exe.addCSourceFiles(.{
            .files = &.{"HelloWorld/HelloWorld.cpp"},
        });
        exe.linkLibrary(lib);
        const run = b.addRunArtifact(exe);
        step.dependOn(&run.step);
    }
}

const base_src_files = [_][]const u8{
    "RegisterTypes.cpp",
    "TriangleGrouper/TriangleGrouperClosestCentroid.cpp",
    "TriangleGrouper/TriangleGrouperMorton.cpp",
    "Physics/Constraints/PointConstraint.cpp",
    "Physics/Constraints/MotorSettings.cpp",
    "Physics/Constraints/DistanceConstraint.cpp",
    "Physics/Constraints/GearConstraint.cpp",
    "Physics/Constraints/Constraint.cpp",
    "Physics/Constraints/ConstraintManager.cpp",
    "Physics/Constraints/PathConstraintPath.cpp",
    "Physics/Constraints/SwingTwistConstraint.cpp",
    "Physics/Constraints/SliderConstraint.cpp",
    "Physics/Constraints/FixedConstraint.cpp",
    "Physics/Constraints/RackAndPinionConstraint.cpp",
    "Physics/Constraints/PathConstraint.cpp",
    "Physics/Constraints/SixDOFConstraint.cpp",
    "Physics/Constraints/PulleyConstraint.cpp",
    "Physics/Constraints/SpringSettings.cpp",
    "Physics/Constraints/ConeConstraint.cpp",
    "Physics/Constraints/TwoBodyConstraint.cpp",
    "Physics/Constraints/HingeConstraint.cpp",
    "Physics/Constraints/ContactConstraintManager.cpp",
    "Physics/Constraints/PathConstraintPathHermite.cpp",
    "Physics/LargeIslandSplitter.cpp",
    "Physics/PhysicsSystem.cpp",
    "Physics/Collision/GroupFilter.cpp",
    "Physics/Collision/ManifoldBetweenTwoFaces.cpp",
    "Physics/Collision/CastConvexVsTriangles.cpp",
    "Physics/Collision/GroupFilterTable.cpp",
    "Physics/Collision/CollideConvexVsTriangles.cpp",
    "Physics/Collision/CastSphereVsTriangles.cpp",
    "Physics/Collision/PhysicsMaterial.cpp",
    "Physics/Collision/NarrowPhaseQuery.cpp",
    "Physics/Collision/BroadPhase/BroadPhaseQuadTree.cpp",
    "Physics/Collision/BroadPhase/QuadTree.cpp",
    "Physics/Collision/BroadPhase/BroadPhase.cpp",
    "Physics/Collision/BroadPhase/BroadPhaseBruteForce.cpp",
    "Physics/Collision/EstimateCollisionResponse.cpp",
    "Physics/Collision/CollideSphereVsTriangles.cpp",
    "Physics/Collision/NarrowPhaseStats.cpp",
    "Physics/Collision/PhysicsMaterialSimple.cpp",
    "Physics/Collision/CollisionDispatch.cpp",
    "Physics/Collision/TransformedShape.cpp",
    "Physics/Collision/Shape/StaticCompoundShape.cpp",
    "Physics/Collision/Shape/MutableCompoundShape.cpp",
    "Physics/Collision/Shape/RotatedTranslatedShape.cpp",
    "Physics/Collision/Shape/OffsetCenterOfMassShape.cpp",
    "Physics/Collision/Shape/TriangleShape.cpp",
    "Physics/Collision/Shape/TaperedCylinderShape.cpp",
    "Physics/Collision/Shape/PlaneShape.cpp",
    "Physics/Collision/Shape/CapsuleShape.cpp",
    "Physics/Collision/Shape/HeightFieldShape.cpp",
    "Physics/Collision/Shape/BoxShape.cpp",
    "Physics/Collision/Shape/ScaledShape.cpp",
    "Physics/Collision/Shape/ConvexHullShape.cpp",
    "Physics/Collision/Shape/SphereShape.cpp",
    "Physics/Collision/Shape/Shape.cpp",
    "Physics/Collision/Shape/MeshShape.cpp",
    "Physics/Collision/Shape/EmptyShape.cpp",
    "Physics/Collision/Shape/TaperedCapsuleShape.cpp",
    "Physics/Collision/Shape/ConvexShape.cpp",
    "Physics/Collision/Shape/CylinderShape.cpp",
    "Physics/Collision/Shape/DecoratedShape.cpp",
    "Physics/Collision/Shape/CompoundShape.cpp",
    "Physics/Collision/CollisionGroup.cpp",
    "Physics/StateRecorderImpl.cpp",
    "Physics/SoftBody/SoftBodyCreationSettings.cpp",
    "Physics/SoftBody/SoftBodyShape.cpp",
    "Physics/SoftBody/SoftBodyMotionProperties.cpp",
    "Physics/SoftBody/SoftBodySharedSettings.cpp",
    "Physics/PhysicsUpdateContext.cpp",
    "Physics/Character/CharacterBase.cpp",
    "Physics/Character/Character.cpp",
    "Physics/Character/CharacterVirtual.cpp",
    "Physics/IslandBuilder.cpp",
    "Physics/Body/MotionProperties.cpp",
    "Physics/Body/BodyCreationSettings.cpp",
    "Physics/Body/MassProperties.cpp",
    "Physics/Body/BodyInterface.cpp",
    "Physics/Body/Body.cpp",
    "Physics/Body/BodyManager.cpp",
    "Physics/PhysicsScene.cpp",
    "Physics/Ragdoll/Ragdoll.cpp",
    "Physics/Vehicle/Wheel.cpp",
    "Physics/Vehicle/VehicleEngine.cpp",
    "Physics/Vehicle/VehicleController.cpp",
    "Physics/Vehicle/VehicleConstraint.cpp",
    "Physics/Vehicle/VehicleTransmission.cpp",
    "Physics/Vehicle/VehicleTrack.cpp",
    "Physics/Vehicle/VehicleCollisionTester.cpp",
    "Physics/Vehicle/TrackedVehicleController.cpp",
    "Physics/Vehicle/WheeledVehicleController.cpp",
    "Physics/Vehicle/VehicleAntiRollBar.cpp",
    "Physics/Vehicle/MotorcycleController.cpp",
    "Physics/Vehicle/VehicleDifferential.cpp",
    "Physics/DeterminismLog.cpp",
    "Math/Vec3.cpp",
    "Skeleton/SkeletonMapper.cpp",
    "Skeleton/SkeletonPose.cpp",
    "Skeleton/SkeletalAnimation.cpp",
    "Skeleton/Skeleton.cpp",
    "TriangleSplitter/TriangleSplitter.cpp",
    "TriangleSplitter/TriangleSplitterBinning.cpp",
    "TriangleSplitter/TriangleSplitterMean.cpp",
    "TriangleSplitter/TriangleSplitterFixedLeafSize.cpp",
    "TriangleSplitter/TriangleSplitterLongestAxis.cpp",
    "TriangleSplitter/TriangleSplitterMorton.cpp",
    "Geometry/OrientedBox.cpp",
    "Geometry/ConvexHullBuilder.cpp",
    "Geometry/Indexify.cpp",
    "Geometry/ConvexHullBuilder2D.cpp",
    "AABBTree/AABBTreeBuilder.cpp",
    "Renderer/DebugRenderer.cpp",
    "Renderer/DebugRendererPlayback.cpp",
    "Renderer/DebugRendererRecorder.cpp",
    "Renderer/DebugRendererSimple.cpp",
    "ObjectStream/ObjectStreamIn.cpp",
    "ObjectStream/ObjectStreamBinaryOut.cpp",
    "ObjectStream/ObjectStreamTextIn.cpp",
    "ObjectStream/ObjectStreamOut.cpp",
    "ObjectStream/ObjectStream.cpp",
    "ObjectStream/ObjectStreamTextOut.cpp",
    "ObjectStream/SerializableObject.cpp",
    "ObjectStream/ObjectStreamBinaryIn.cpp",
    "ObjectStream/TypeDeclarations.cpp",
    "Core/Semaphore.cpp",
    "Core/TickCounter.cpp",
    "Core/RTTI.cpp",
    "Core/JobSystemSingleThreaded.cpp",
    "Core/JobSystemWithBarrier.cpp",
    "Core/Profiler.cpp",
    "Core/LinearCurve.cpp",
    "Core/IssueReporting.cpp",
    "Core/Color.cpp",
    "Core/Memory.cpp",
    "Core/StringTools.cpp",
    "Core/JobSystemThreadPool.cpp",
    "Core/Factory.cpp",
};
